apiVersion: apps/v1
kind: Deployment
metadata:
  name: sillytavern-deployment
spec:
  replicas: 12
  selector:
    matchLabels:
      app: sillytavern
  template:
    metadata:
      labels:
        app: sillytavern
    spec:
      containers:
      - name: sillytavern
        image: ghcr.io/sillytavern/sillytavern:latest
        ports:
        - containerPort: 8000