apiVersion: v1
kind: Service
metadata:
  name: sillytavern-service-yaml
spec:
  type: LoadBalancer
  selector:
    app: sillytavern
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
