pipeline {
    agent any

    environment {
        APP_NAME = 'my-nestjs-app'
        DOCKER_IMAGE = "my-nestjs-app:${env.BUILD_ID}"
    }

    stages {
        stage('Build') {
            steps {
                dir('ITE/GCL1/MD419430/Sprawozdanie1') {
                    sh 'docker build -t ${APP_NAME}-builder -f Dockerfile.build ./work/typescript-starter/'
                }
            }
        }
        stage('Test') {
            steps {
                dir('ITE/GCL1/MD419430/Sprawozdanie1') {
                    sh 'docker build -t ${APP_NAME}-tester -f Dockerfile.test --build-arg BASE_IMAGE=${APP_NAME}-builder ./work/typescript-starter/'
                    sh 'docker run --rm ${APP_NAME}-tester npm run test'
                }
            }
        }
        stage('Publish') {
            steps {
                dir('ITE/GCL1/MD419430/Sprawozdanie1') {
                    sh "docker save ${APP_NAME}-tester -o build-artifact.tar"
                    archiveArtifacts artifacts: 'build-artifact.tar', allowEmptyArchive: false
                }
            }
        }
        stage('Deploy') {
            steps {
                sh "docker run -d --name ${APP_NAME}-run-${env.BUILD_ID} -p 3000:3000 ${APP_NAME}-tester npm run start"
            }
        }
    }
}