FROM node:18-slim

RUN apt-get update -o Acquire::Check-Valid-Until=false && apt-get install -y git

WORKDIR /app

RUN git clone https://github.com/expressjs/express.git

WORKDIR /app/express

RUN npm install
