FROM node:18-slim

RUN apt-get -o Acquire::Check-Valid-Until=false update && apt-get install -y --no-install-recommends git && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN git clone https://github.com/expressjs/express.git

WORKDIR /app/express

RUN npm install
