version: '3.8'

services:

  app-build:
    build:
      context: .
      dockerfile: Dockerfile.build
    image: shortener-final-build


  app-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    image: shortener-final-test
    depends_on:
      - app-build

    command: npm test