---
# Sanity check
- name: Sanity check 
  ansible.builtin.shell: df -h / | tail -1 | awk '{print $4}'
  register: disk_space
  ignore_errors: yes

- name: Wyświetlenie wyniku sanity check
  ansible.builtin.debug:
    msg: "Dostępne miejsce: {{ disk_space.stdout }}"

# Instalacja dockera
- name: Instalacja Docker
  ansible.builtin.apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Uruchomienie usługi Docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

# Wysłanie i przygotowanie aplikacji
- name: Tworzenie folderu na aplikację
  ansible.builtin.file:
    path: /home/ansible/app_deploy
    state: directory

- name: Wysłanie i rozpakowanie artefaktu
  ansible.builtin.unarchive:
    src: nestjs-app-v17.tar.gz
    dest: /home/ansible/app_deploy/

#Uruchomienie w konetenerze
- name: Uruchomienie kontenera z aplikacją
  community.docker.docker_container:
    name: nestjs_app
    image: node:18-alpine
    state: started
    volumes:
      - /home/ansible/app_deploy:/app
    working_dir: /app
    command: "node dist/main.js"
    ports:
      - "3000:3000"

# Sanity check wdrozenia 
- name: Czekam 5 sekund na start...
  ansible.builtin.pause:
    seconds: 5

- name: Weryfikacja działania 
  ansible.builtin.uri:
    url: "http://localhost:3000"
    status_code: 200
  register: web_result

- name: Potwierdzenie weryfikacji
  ansible.builtin.debug:
    msg: "Aplikacja odpowiada poprawnie!"
  when: web_result.status == 200

# Cleanup
- name: Zatrzymanie i usunięcie kontenera
  community.docker.docker_container:
    name: nestjs_app
    state: absent

- name: Usunięcie plików aplikacji
  ansible.builtin.file:
    path: /home/ansible/app_deploy
    state: absent