---
- name: Wdrozenie artefaktu i weryfikacja w kontenerze
  hosts: Endpoints
  become: yes
  tasks:
    - name: 1. sprawdzenie zajetosci dysku
      command: df -h /
      register: disk_space
      ignore_errors: yes

    - name: 1b. Wyswietlenie wyniku dysku
      debug:
        msg: "Stan dysku docelowego:\n{{ disk_space.stdout }}"

    - name: 2. Pobieranie Dockera
      get_url:
        url: https://get.docker.com/
        dest: /tmp/get-docker.sh
        mode: '0755'

    - name: 3. Instalacja dockera
      command: /tmp/get-docker.sh
      args:
        creates: /usr/bin/docker

    - name: 4. Sprawdzenie stanu uslugi docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: 5. Wysłanie paczki .deb na host docelowy
      copy:
        src: nlohmann-json-lib.deb
        dest: /tmp/nlohmann-json-lib.deb

    - name: 6. Stworzenie kontenera testowego (Sandbox) do weryfikacji dzialania naszej paczki .deb
      command: docker run -d --name test-sandbox -v /tmp:/tmp ubuntu:22.04 sleep 600

    - name: 7. Instalacja paczki .deb w kontenerze testowym
      command: docker exec test-sandbox dpkg -i /tmp/nlohmann-json-lib.deb

    - name: 8. Weryfikacja dzialania aplikacji (sample-app) w kontenerze testowym
      command: docker exec test-sandbox sample-app
      register: app_output

    - name: 9. Wyswietlenie wyniku dzialania sample-app w kontenerze testowym
      debug:
        msg: "Wynik dzialania sample-app: {{ app_output.stdout }}"

    - name: 10. Oczysczanie srodowiska (Usun kontener testowy)
      command: docker rm -f test-sandbox
      ignore_errors: yes

    - name: 11. Oczysczanie srodowiska (Usun paczke .deb z hosta docelowego)
      file:
        path: /tmp/nlohmann-json-lib.deb
        state: absent