FROM fedora

RUN dnf -y install git make gcc automake autoconf libtool gettext-devel po4a

RUN git clone https://github.com/tukaani-project/xz.git

WORKDIR /xz

RUN ./autogen.sh
RUN ./configure
RUN make