galaxy_info:
  author: Yehor
  description: >
    Wdraża artefakt readme-aura (.tgz) na maszynę docelową.
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble

dependencies: []
