pipeline 
{
    agent any
    
    stages 
    {
        stage('Budowa i testy') 
        {
            steps 
            {
                sh 'docker build --target test -t cjson-app:test .'
            }
        }
        
        stage('Deploy') 
        {
            steps 
            {
                sh 'docker build --target deploy -t cjson-app:${BUILD_NUMBER} .'
            }
        }
        
        stage('Smoke Test')
         {
            steps 
            {
                sh 'docker run --rm --name smoke_test cjson-app:${BUILD_NUMBER}'
            }
        }
        
        stage('Publikacja artefaktu')
         {
            steps 
            {
                sh 'docker save -o cjson-artifact-${BUILD_NUMBER}.tar cjson-app:${BUILD_NUMBER}'
                archiveArtifacts artifacts: '*.tar', fingerprint: true
            }
        }
    }
}