pipeline {
    agent any
    
    environment 
    {
        SCIEZKA_ROBOCZA = 'ITE/GCL1/LC417617/Sprawozdanie2/Zajecia6'
    }

    stages {
        stage('Budowa i testy') 
        {
            steps 
            {
                dir(env.SCIEZKA_ROBOCZA) 
                {
                    sh 'docker build --target test -t cjson-app:test .'
                }
            }
        }
        
        stage('Deploy') 
        {
            steps 
            {
                dir(env.SCIEZKA_ROBOCZA)
                 {
                    sh 'docker build --target deploy -t cjson-app:${BUILD_NUMBER} .'
                }
            }
        }
        
        stage('Smoke Test') 
        {
            steps 
            {
                sh 'docker run --rm --name smoke_test_${BUILD_NUMBER} cjson-app:${BUILD_NUMBER}'
            }
        }
        
        stage('Publikacja artefaktu')
        {
            steps 
            {
                dir(env.SCIEZKA_ROBOCZA) 
                {
                    sh 'docker save -o cjson-artifact-${BUILD_NUMBER}.tar cjson-app:${BUILD_NUMBER}'
                    archiveArtifacts artifacts: '*.tar', fingerprint: true
                }
            }
        }
    }
}