apiVersion: apps/v1
kind: Deployment
metadata:
  name: profesjonalne-wdrozenie
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nestjs-super-apka
  template:
    metadata:
      labels:
        app: nestjs-super-apka
    spec:
      containers:
      - name: kontener-nestjs
        image: nestjs-projekt
        imagePullPolicy: Never
        ports:
        - containerPort: 3000