- name: Procedury zdalne
  hosts: all
  tasks:
    - name: Ping
      ansible.builtin.ping:

- name: Zadania na Endpoints
  hosts: Endpoints
  become: yes
  tasks:
    - name: Kopiowanie pliku inwentory.ini
      ansible.builtin.copy:
        src: inventory.ini
        dest: /home/ansible/inventory.ini

    - name: Odświeżenie listy pakietów (apt update)
      ansible.builtin.apt:
        update_cache: yes

    - name: Aktualizacja wszystkich pakietów (apt upgrade)
      ansible.builtin.apt:
        upgrade: yes

    - name: Instalacja pakietu rng-tools (dostarcza usługę rngd)
      ansible.builtin.apt:
        name: rng-tools-debian
        state: present

    - name: Restart usług
      ansible.builtin.service:
        name: "{{ item }}"
        state: restarted
      loop:
        - ssh
        - rng-tools-debian
 