version: '3.8'

services:
  docker-dind:
    image: docker:dind
    privileged: true
    networks:
      jenkins-net:
          aliases:
            - docker
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home

  jenkins:
    build: .
    user: root
    networks:
      - jenkins-net
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    ports:
      - "8080:8080"
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    depends_on:
      - docker-dind

networks:
  jenkins-net:

volumes:
  jenkins-data:
  jenkins-docker-certs:
