pipeline {
    agent {
        docker {
            image 'docker:latest'
            args '-u root  -v /var/run/docker.sock:/var/run/docker.sock'
            reuseNode true
        }
    }

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/InzynieriaOprogramowaniaAGH/MDO2026s_ITE.git',
                    branch: 'KK419817'
            }
        }

        stage('Build') {
            steps {
                dir('ITE/GCL3/KK419817/Sprawozdanie2/') {
                    sh 'docker build --no-cache -f Dockerfile.build -t express-build .'
                }
            }
        }

        stage('Test') {
            steps {
                dir('ITE/GCL3/KK419817/Sprawozdanie2/') {
                    sh 'docker build --no-cache -f Dockerfile.test -t express-test .'
                    sh 'docker run --rm express-test'
                }
            }
        }

        stage('Deploy') {
            steps {
                dir('ITE/GCL3/KK419817/Sprawozdanie2/') {
                }
            }
        }

        stage('Publish') {
            steps {
                dir('ITE/GCL3/KK419817/Sprawozdanie2/') {
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline success'
        }
        failure {
            echo 'Pipeline failed'
        }
    }
}