pipeline {
    agent any

    environment {
        DOCKERHUB_USER = 'zucho'
        IMAGE_NAME = 'express-deploy'
        BUILD_IMAGE = 'express-bldr:latest'
        TEST_IMAGE = 'express-tester:latest'
        DEPLOY_IMAGE = 'zucho/express-deploy'
        VERSION = "v${BUILD_NUMBER}"
    }

    stages {
        stage('Clean') {
            steps {
                deleteDir()
            }
        }

        stage('Clone') {
            steps {
                checkout scm
                sh 'ls -la'
                sh 'ls -la MZ422009/Sprawozdanie2'
            }
        }

        stage('Build') {
            steps {
                dir('MZ422009/Sprawozdanie2') {
                    sh 'docker build --no-cache -f Dockerfile.bld -t $BUILD_IMAGE .'
                }
            }
        }

        stage('Test') {
            steps {
                dir('MZ422009/Sprawozdanie2') {
                    sh 'docker build --no-cache -f Dockerfile.test -t $TEST_IMAGE .'
                    sh 'docker run --rm $TEST_IMAGE'
                }
            }
        }

        stage('Deploy') {
            steps {
                dir('MZ422009/Sprawozdanie2') {
                    sh 'docker build --no-cache -f Dockerfile.deploy -t $DEPLOY_IMAGE:$VERSION -t $DEPLOY_IMAGE:latest .'
                    sh 'docker run --rm $DEPLOY_IMAGE:$VERSION'
                }
            }
        }

        stage('Publish') {
            steps {
                sh 'docker push $DEPLOY_IMAGE:$VERSION'
                sh 'docker push $DEPLOY_IMAGE:latest'
                sh 'docker save $DEPLOY_IMAGE:$VERSION | gzip > express-deploy-${BUILD_NUMBER}.tar.gz'
                archiveArtifacts artifacts: "express-deploy-${BUILD_NUMBER}.tar.gz", fingerprint: true
            }
        }
    }
}
