FROM node:20

WORKDIR /readme-aura

RUN apt-get update && apt-get install -y --no-install-recommends git \
    && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/collectioneur/readme-aura.git .

RUN npm install

RUN npm run build

