services:
  readme-aura-build:
    build:
      context: .
      dockerfile: ./Dockerfile.build
    image: mdo-ite:sprawozdanie3-build

  readme-aura-test:
    build:
      context: .
      dockerfile: ./Dockerfile.test
    image: mdo-ite:sprawozdanie3-test
    depends_on:
      - readme-aura-build

  readme-aura-deploy:
    build:
      context: .
      dockerfile: ./Dockerfile.deploy
    image: mdo-ite:sprawozdanie6-deploy
    depends_on:
      - readme-aura-build

