FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    git \
    build-essential \
    cmake \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN git clone --depth 1 https://github.com/nlohmann/json.git .

RUN cmake -S . -B build -DJSON_BuildTests=On

RUN cmake --build build