FROM fedora:latest
RUN dnf -y install gcc make autoconf automake libtool gettext-devel tar && dnf clean all

WORKDIR /workspace


COPY xz /workspace/xz


WORKDIR /workspace/xz
RUN ./autogen.sh && \
    ./configure --prefix=/usr/local && \
    make -j$(nproc) && \
    make install DESTDIR=/wyjscie/xz_zbudowane