pipeline {
    agent any
    stages {
        stage('Przygotowanie') {
            steps {
                cleanWs()
                checkout scm // Pobiera Twojego brancha ze wszystkim w lab06
            }
        }
        
       stage('Build & Deploy') {
            steps {
                script {
                    dir('Lab06') { // Pamiętaj o wielkości liter!
                        echo "UWAGA! Sprawdzam, gdzie jestem i co tu leży:"
                        sh 'pwd'
                        sh 'ls -la'
                        
                        // Reszta po staremu:
                        sh 'docker build -t xzbld -f Dockerfile.xz.bld .'
                        // ...
                        sh 'docker build -t xzbld -f Dockerfile.xz.bld .'
                        sh 'docker build -t xz-deploy -f Dockerfile.xz.deploy .'
                        
                        // Test strumieniowy (schemat z tablicy)
                        sh 'echo "Dupa" > input.txt && gzip -c input.txt > input.gz'
                        sh 'cat input.gz | docker run -i --rm xz-deploy > out.xz'
                        sh 'test -s out.xz'
                    }
                }
            }
        }
        
        stage('Artefakty') {
            steps {
                dir('Lab06') {
                    sh 'docker create --name temp xzbld'
                    sh 'docker cp temp:/wyjscie/xz_zbudowane ./binaria'
                    sh 'docker rm temp'
                    sh 'tar -czvf program.tar.gz ./binaria'
                    archiveArtifacts artifacts: 'program.tar.gz'
                }
            }
        }
    }
}