FROM node:20

RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN git clone https://github.com/nestjs/typescript-starter.git .

RUN npm install
RUN npm run build

CMD ["npm", "run", "start:prod"]