FROM node:20-alpine

#ustawienie katalogu roboczego
WORKDIR /app

#kopia gotowego folderu do kontenera
RUN git clone -b 4.x https://github.com/expressjs/express.git .

#wejscie do folderu i instalacja
WORKDIR /app
RUN npm install