FROM node:20-alpine

#ustawienie katalogu roboczego
WORKDIR /app

#kopia gotowego folderu do kontenera
RUN git clone -b 4.x https://github.com/expressjs/express.git ./express/

#wejscie do folderu i instalacja
WORKDIR /app/express
RUN npm install