- name: playbook
  hosts: all
  tasks:
    - name: ping wszytkich maszyn
      ansible.builtin.ping:

    - name: kopiowanie pliku inwentaryzacji
      ansible.builtin.copy:
        src: ./inventory.ini
        dest: /home/ansible/inventory_fedora.ini
        owner: ansible
        group: ansible
        mode: '0644'
      when: "'Endpoints' in group_names"

- name: Administracja systemem Fedora
  hosts: Endpoints
  become: yes
  tasks:
    - name: Aktualizacja pakietow (dnf update)
      ansible.builtin.shell: dnf update -y

    - name: Instalacja pakietu rng-tools (jesli nie ma)
      ansible.builtin.shell: dnf install -y rng-tools
      ignore_errors: true

    - name: Restart uslug sshd oraz rngd
      ansible.builtin.service:
        name: "{{ item }}"
        state: restarted
      loop:
        - sshd
        - rngd
      ignore_errors: true