FROM maven:3.9.6-eclipse-temurin-17
RUN apt-get update && apt-get install -y git ca-certificates && rm -rf /var/lib/apt/lists/*
WORKDIR /usr/src/mymaven
RUN git clone https://github.com/stleary/JSON-java.git .
RUN mvn compile
CMD ["/bin/bash"]