FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y \
    git build-essential autoconf automake libtool pkg-config flex bison \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt

RUN git clone https://github.com/jqlang/jq.git
WORKDIR /opt/jq

RUN git submodule update --init && \
    autoreconf -i && \
    ./configure --with-oniguruma=builtin && \
    make -j"$(nproc)"

CMD ["/bin/bash"]
