FROM jq-build:local

WORKDIR /opt/jq

COPY jq-functional-tests.sh /usr/local/bin/jq-functional-tests.sh

RUN chmod +x /usr/local/bin/jq-functional-tests.sh

CMD ["/usr/local/bin/jq-functional-tests.sh"]
