FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive
ARG JQ_VERSION=jq-1.8.1

RUN apt-get update && apt-get install -y \
    git \
    ca-certificates \
    build-essential \
    autoconf \
    automake \
    libtool \
    pkg-config \
    flex \
    bison \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt

RUN git clone --depth 1 --branch ${JQ_VERSION} https://github.com/jqlang/jq.git

WORKDIR /opt/jq

RUN git submodule update --init --depth 1 && \
    autoreconf -i && \
    ./configure --with-oniguruma=builtin && \
    make -j"$(nproc)"

RUN ./jq --version

CMD ["/bin/bash"]
