FROM node:22

WORKDIR /app

RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*
RUN git clone --depth 1 https://github.com/fastify/fastify.git ./fastify-repo

RUN cd ./fastify-repo && npm install

RUN npm install ./fastify-repo

RUN echo "const fastify = require('fastify')({ logger: true }); \
          console.log('--- APLIKACJA STARTUJE ---'); \
          const start = async () => { \
            try { \
              await fastify.listen({ port: 3000, host: '0.0.0.0' }); \
              console.log('--- SERWER DZIAŁA NA PORCIE 3000 ---'); \
            } catch (err) { \
              console.error('--- BŁĄD PODCZAS STARTU ---'); \
              console.error(err); \
              process.exit(1); \
            } \
          }; \
          start();" > app.js

CMD ["node", "app.js"]