RUN echo "const fastify = require('fastify')({ logger: true }); \
          \
          fastify.get('/', async (request, reply) => { \
            reply.type('text/html').send('<h1>Witaj w mojej aplikacji!</h1><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt.</p>'); \
          }); \
          \
          const start = async () => { \
            try { \
              await fastify.listen({ port: 3000, host: '0.0.0.0' }); \
              console.log('--- SERWER DZIAŁA NA PORCIE 3000 ---'); \
            } catch (err) { \
              console.error('--- BŁĄD PODCZAS STARTU ---'); \
              process.exit(1); \
            } \
          }; \
          start();" > app.js