FROM ubuntu:24.04
ENV DEBIAN_FRONTEND=noninteractive
# zależności neovim bez gita
RUN apt-get update && apt-get install -y \
    ninja-build gettext cmake unzip curl build-essential \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /workspace
CMD ["/bin/bash"]
