pipeline {
    agent {
        docker { 
            image 'node:20-alpine'
            args '-u root:root'
        }
    }

    stages {
        stage('Build') {
            steps {
                echo 'Instalacja zależności NPM...'
                sh 'npm ci'
            }
        }
        stage('Test') {
            steps {
                echo 'Uruchamianie testów...'
                sh 'npm test'
            }
        }
    }
}