pipeline {
    agent any

    stages {
        stage('1. Build') {
            steps {
                dir('ITE/GCL3/MK421268/lab5') {
                    echo 'Budowanie obrazu bazowego z kodem...'
                    sh 'docker build -t express-build-image:latest -f Dockerfile.build .'
                }
            }
        }

        stage('2. Test') {
            steps {
                dir('ITE/GCL3/MK421268/lab5') {
                    echo 'Budowanie i uruchamianie kontenera testowego...'
                    sh 'docker build -t express-test-image:latest -f Dockerfile.test .'
                    sh 'docker run --rm express-test-image:latest'
                }
            }
        }
    }
}