FROM ubuntu:24.04

# Optymalizacja: polskie serwery lustrzane
RUN sed -i 's/archive.ubuntu.com/pl.archive.ubuntu.com/g' /etc/apt/sources.list.d/ubuntu.sources && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
    ca-certificates ninja-build gettext cmake unzip curl git build-essential \
    file dpkg-dev && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /workspace

RUN git clone https://github.com/neovim/neovim.git .

# Budowanie Neovima z flagą optymalizacji
RUN make -j$(nproc) CMAKE_BUILD_TYPE=RelWithDebInfo

# Generowanie paczki .deb (zgodnie z prawą stroną rysunku - paczka z zależnościami)
RUN cd build && cpack -G DEB