FROM python:3.13-slim

WORKDIR /app

COPY . .

RUN apt-get update
RUN apt-get install -y build-essential git
RUN apt-get clean

# RUN git clone https://github.com/blankdots/minimalpy.git .

RUN pip install --upgrade pip
RUN pip install -r ITE/GCL3/MŻ422030/minimalpy-jenkins/minimalpy/requirements.txt
RUN pip install pytest

CMD ["bash"]