FROM python:3.12-slim
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

WORKDIR /app
RUN git clone --depth 1 https://github.com/pallets/flask.git .

RUN sed -i 's/name = "Flask"/name = "olek-devopsolek-lab7"/' pyproject.toml

RUN pip install --no-cache-dir .[test,async] build
RUN python -m build 