apiVersion: apps/v1
kind: Deployment
metadata:
  name: apka-recreate
spec:
  replicas: 4
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: moja-apka
  template:
    metadata:
      labels:
        app: moja-apka
    spec:
      containers:
      - name: web
        image: moja-apka-webowa:v1
        imagePullPolicy: Never