apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-recreate
spec:
  replicas: 4
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: myapp-rec
  template:
    metadata:
      labels:
        app: myapp-rec
    spec:
      containers:
      - name: myapp
        image: myapp:v2
        imagePullPolicy: Never
