FROM eclipse-temurin:17-jre
WORKDIR /app
RUN apt-get update && apt-get install -y jq && rm -rf /var/lib/apt/lists/*
COPY target/aplikacja.jar app.jar
COPY output.json .
CMD ["java", "-jar", "app.jar"]