pipeline {
    agent any
    stages {
        stage('Collect') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps{
                sh 'docker build -t json-java-build:latest -f ITE/GCL1/MB421332/Sprawozdanie2/Dockerfile.builder .'
            }
        }
        stage('Test'){
            steps{
                echo 'test'
            }
        }
    }
}