pipeline {
    agent any
    stages {
        stage('Collect') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps{
                sh 'docker build -t json-java-build:latest -f Dockerfile.builder .'
            }
        }
        stage('Test'){
            steps{
                sh 'mvn test > test_results.log || true'
                sh 'cat test_results.log'
            }
        }
    }
}