pipeline {
    agent any
    stages {
        stage('Collect') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            sh 'docker build -t json-java-build:latest -f Dockerfile.builder .'
        }
        stage('Test'){

        }
    }
}