FROM fedora:latest

RUN dnf install -y openssh-server && dnf clean all

RUN ssh-keygen -A

RUN echo 'root:root' | chpasswd

RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]