---
- name: Niedostępny endpoint
  hosts: Endpoints
  gather_facts: false
  ignore_unreachable: true

  tasks:
    - name: Próba ping Ansible do endpoita
      ansible.builtin.ping:
      register: ping_result
      failed_when: false

    - name: wynik próby połączenia
      ansible.builtin.debug:
        var: ping_result
