FROM ubuntu:24.04

RUN sed -i 's/archive.ubuntu.com/pl.archive.ubuntu.com/g' /etc/apt/sources.list.d/ubuntu.sources && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
    ninja-build gettext cmake unzip curl git build-essential && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /workspace

RUN git clone https://github.com/neovim/neovim.git .

RUN make -j$(nproc) CMAKE_BUILD_TYPE=RelWithDebInfo