FROM neovim-builder-jenkins:latest

# 'tester' z katalogiem domowym
RUN useradd -m tester && \
    # folder z kodem, żeby mógł go kompilować/testować
    chown -R tester:tester /workspace

# Przełączamy się na tego użytkownika 
USER tester
WORKDIR /workspace

CMD["make", "unittest"]