FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    ninja-build gettext cmake unzip curl git build-essential \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace

RUN git clone https://github.com/neovim/neovim.git .

RUN make CMAKE_BUILD_TYPE=RelWithDebInfo

CMD ["/bin/bash"]