---
- name: Sanity check
  hosts: Endpoints
  become: yes

  tasks:
    - name: Check SSH service
      ansible.builtin.service:
        name: ssh
        state: started

    - name: Check Docker service
      ansible.builtin.service:
        name: docker
        state: started

    - name: Check Docker version
      ansible.builtin.command:
        cmd: docker --version
      register: docker_version

    - name: Show Docker version
      ansible.builtin.debug:
        var: docker_version.stdout
