FROM ubuntu:24.04 AS builder

LABEL maintainer="lcurylo@student.agh.edu.pl"
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    git \
    cmake \
    build-essential \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN git clone https://github.com/DaveGamble/cJSON.git .

RUN mkdir build && cd build && cmake .. -DENABLE_CJSON_TEST=On && make