apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-canary-new
  labels:
    app: nginx-canary
    track: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-canary
      track: canary
  template:
    metadata:
      labels:
        app: nginx-canary
        track: canary
    spec:
      containers:
        - name: nginx
          image: nginx:1.26
          ports:
            - containerPort: 80
