apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy
  labels:
    app: web
    track: rolling
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 30%
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
        track: rolling
    spec:
      containers:
        - name: web
          image: web-custom:v2
          ports:
            - containerPort: 80