---
repo_url: "https://github.com/InzynieriaOprogramowaniaAGH/MDO2026s_ITE.git"
repo_version: "MD419430"
repo_dir: "/opt/nest-repo"
app_dir: "/opt/nest-repo/ITE/GCL1/MD419430/Sprawozdanie1/work/typescript-starter"

local_image: "nest-app:local"
local_container: "nest-local"

published_image: "mateuszdoktor1/nest-app:3"
published_container: "nest-published"

app_port: 3000
health_url: "http://localhost:3000/"

cleanup: true