apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-recreate
spec:
  replicas: 4
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
        version: v2
    spec:
      containers:
      - name: app
        image: app:v2
        imagePullPolicy: Never