galaxy_info:
  author: maksluczak
  description: Deploys QR code .NET library and verifies generation
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
  galaxy_tags:
    - docker
    - dotnet
    - qrcode

dependencies: []