---
- name: Playbook 1
  hosts: Endpoints
  become: yes
  tasks:
    - name: Ping endpoints
      ansible.builtin.ping:

    - name: Copy inventory.ini to /tmp/
      ansible.builtin.copy:
        src: inventory.ini
        dest: /tmp/inventory.ini

    - name: Second ping
      ansible.builtin.ping:

    - name: Cache update
      ansible.builtin.apt:
        update_cache: yes

    - name: Package upgrade
      ansible.builtin.apt:
        upgrade: dist

    - name: Sshd restart
      ansible.builtin.service:
        name: ssh
        state: restarted

    - name: Rngd restart
      ansible.builtin.service:
        name: rngd
        state: restarted
      ignore_errors: yes