apiVersion: apps/v1
kind: Deployment
metadata:
  name: lc417617-recreate
  labels:
    app: lc417617-recreate
spec:
  replicas: 4
  selector:
    matchLabels:
      app: lc417617-recreate
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: lc417617-recreate
    spec:
      containers:
        - name: web
          image: lc417617-k8s-demo:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 80
