apiVersion: apps/v1
kind: Deployment
metadata:
  name: lc417617-rolling
  labels:
    app: lc417617-rolling
spec:
  replicas: 4
  selector:
    matchLabels:
      app: lc417617-rolling
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 50%
  template:
    metadata:
      labels:
        app: lc417617-rolling
    spec:
      containers:
        - name: web
          image: lc417617-k8s-demo:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 80
