FROM my-builder
RUN apt-get update && apt-get install -y cmake && rm -rf /var/lib/apt/lists/*
WORKDIR /app
RUN cmake -S . -B build -DJSON_BuildTests=On
RUN cmake --build build --parallel 4
WORKDIR /app/build
RUN ctest --output-on-failure && cd .. && rm -rf build