#!/bin/bash
commit_msg=$(cat "$1")
if [[ ! $commit_msg =~ ^AP421868 ]]; then
  echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
  echo "BŁĄD: Zacznij wiadomość od AP421868!"
  echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
  exit 1
fi