---
galaxy_info:
  author: "Mateusz"
  description: "Build, run, verify and clean container artifacts"
  license: "MIT"
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
dependencies: []
