pipeline {
    agent {
        dockerfile { 
            dir 'ITE/GCL1/OD423299/Sprawozdanie2/jenkins-zlib-test'
            args '-u root' 
        }
    }

    stages {
        stage('Build (Kompilacja)') {
            steps {
                sh '''
                    echo "Kompilacja pliku pobranego z Gita..."
                    gcc -o wrapper.bin ITE/GCL1/OD423299/Sprawozdanie2/jenkins-zlib-test/src/wrapper.c -lz
                '''
            }
        }
        stage('Pakowanie (Niezależne)') {
            steps {
                sh '''
                    echo "Test integralności zlib w CI/CD" > test.txt
                    md5sum test.txt | awk "{print $1}" > original.md5
                    
                    gzip -c test.txt > test.txt.gz
                '''
            }
        }

        stage('Test MD5 (C1)') {
            steps {
                sh '''
                    ./wrapper.bin test.txt.gz > wynik.txt
                    
                    ORIG_MD5=$(md5sum test.txt | cut -d' ' -f1)
                    CURR_MD5=$(md5sum wynik.txt | cut -d' ' -f1)
                    
                    echo "MD5 przed: $ORIG_MD5"
                    echo "MD5 po:    $CURR_MD5"
                    
                    if [ "$ORIG_MD5" = "$CURR_MD5" ]; then
                        echo "Weryfikacja powiodłą się"
                    else
                        echo "BŁĄD: Dane uległy uszkodzeniu!"
                        exit 1
                    fi
                '''
            }
        }

        stage('Pakowanie .DEB') {
            steps {
                sh '''
                    mkdir -p pkg/DEBIAN pkg/usr/bin
                    cp wrapper.bin pkg/usr/bin/zlib-tool
                    
                    cat <<EOF > pkg/DEBIAN/control
Package: zlib-wrapper-tool
Version: 1.0.0
Architecture: amd64
Maintainer: Jenkins
Description: Narzedzie do dekompresji GZIP oparte na zlib
EOF
                    dpkg-deb --build pkg zlib-tool.deb
                '''
            }
        }
    }

    stage('Deploy (Wdrożenie Sandbox)') {
            steps {
                sh '''
                    echo "Instalacja paczki na serwerze docelowym"
                    dpkg -i zlib-tool.deb
                    
                    echo "Weryfikacja działania"                    
                    /usr/bin/zlib-tool || true
                    
                    echo "Deploy udany"
                '''
            }
        }

    post {
        success {
            archiveArtifacts artifacts: 'zlib-tool.deb', fingerprint: true
        }
    }
        
}