---
- name: Podstawowa konfiguracja maszyn
  hosts: Endpoints
  become: yes
  tasks:
    - name: 1. Skopiowanie pliku inwentaryzacji
      ansible.builtin.copy:
        src: inventory.ini
        dest: /tmp/inventory.ini

    - name: 2. Aktualizacja pakietow systemowych
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist

    - name: 3. Instalacja rng-tools-debian (wymagane dla usługi rngd)
      ansible.builtin.apt:
        name: rng-tools-debian
        state: present

    - name: 4. Restart uslug sshd i rngd
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: restarted
      loop:
        - ssh
        - rng-tools-debian
