#!/bin/bash

commit_msg_file=$1
commit_msg=$(head -n 1 "$commit_msg_file")
prefix="LZ423170"

if [[ ! "$commit_msg" = $prefix ]]; then
  echo "ERROR: Commit message must start with 'LZ423170'"
  exit 1
fi