- name: Podstawowe operacje systemowe
  hosts: all
  become: yes
  tasks:
    - name: 1. Wyslanie zadania ping
      ansible.builtin.ping:

    - name: 2. Kopiowanie pliku inwentaryzacji na Endpoints
      ansible.builtin.copy:
        src: inventory.ini
        dest: /tmp/inventory.ini
      when: "'Endpoints' in group_names"

    - name: 3. Aktualizacja pakietow
      ansible.builtin.apt:
        update_cache: yes
        upgrade: yes
      ignore_errors: yes

    - name: 4. Restart uslugi sshd
      ansible.builtin.systemd:
        name: sshd
        state: restarted
      ignore_errors: yes

    - name: 5. Restart uslugi rngd
      ansible.builtin.systemd:
        name: rng-tools
        state: restarted
      ignore_errors: yes
