server {
    listen 8888;
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        
        add_header X-Zbudowane-Przez "Oskar";
        add_header X-Numer-Lab "Lab10";
    }
}