apiVersion: apps/v1
kind: Deployment
metadata:
  name: oskar-web-deployment
  labels:
    app: oskar-web
spec:
  replicas: 4
  selector:
    matchLabels:
      app: oskar-web
  template:
    metadata:
      labels:
        app: oskar-web
    spec:
      containers:
      - name: nginx-container
        image: oskar-nginx:broken
        imagePullPolicy: Never
        ports:
        - containerPort: 8888