apiVersion: apps/v1
kind: Deployment
metadata:
  name: oskar-web-stable
  labels:
    app: oskar-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: oskar-web
      track: stable
  template:
    metadata:
      labels:
        app: oskar-web
        track: stable
    spec:
      containers:
      - name: nginx-container
        image: oskar-nginx:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 8888