- name: Zadania Lab 8
  hosts: Endpoints
  become: true
  tasks:
    - name: Test polaczenia ping
      ansible.builtin.ping:

    - name: Aktualizacja pakietów
      ansible.builtin.package:
        name: "*"
        state: latest

    - name: Restart uslug
      ansible.builtin.service:
        name: "{{ item }}"
        state: restarted
      loop:
        - ssh
