# Generated by Anaconda 44.14
# Keyboard layouts
keyboard --vckeymap=pl --xlayouts='pl'
# System language
lang pl_PL.UTF-8

# Network information
network  --hostname=rawhide.ziplabs.metal.agh.edu.pl.local

%packages
@^server-product-environment

%end

# System authorization information
authselect enable-feature with-fingerprint

# Run the Setup Agent on first boot
firstboot --enable

# Source
url --mirrorlist=http://mirrors.fedoraproject.org/mirrorlist?repo=fedora-44&arch=x86_64
repo --name=update --mirrorlist=http://mirrors.fedoraproject.org/mirrorlist?repo=updates-released-f44&arch=x86_64

# Generated using Blivet version 3.13.1
ignoredisk --only-use=sda
# Partition clearing information
clearpart --all
# Disk partitioning information
part /boot/efi --fstype="efi" --ondisk=sda --size=600 --fsoptions="umask=0077,shortname=winnt"
part btrfs.404 --fstype="btrfs" --ondisk=sda --size=46502
part /boot --fstype="ext4" --ondisk=sda --size=2048
btrfs none --label=fedora_fedora --data=single btrfs.404
btrfs / --subvol --name=root LABEL=fedora_fedora

# System timezone
timezone Europe/Warsaw --utc

#Root password
rootpw --lock
user --groups=wheel --name=kamilek --password=abc0 --plaintext --gecos "Kamil"
