FROM node:22-bookworm-slim

# Tworzymy i ustawiamy katalog roboczy
WORKDIR /app

# Kopiujemy najpierw same pliki konfiguracyjne pakietów
# (to pozwala na lepsze cache'owanie warstw Dockera)
COPY package.json package-lock.json ./

# Czysta instalacja zależności projektu (npm ci gwarantuje zgodność z lockfile)
RUN npm ci

# Kopiujemy resztę kodu źródłowego
COPY . .

# Budujemy aplikację NestJS (wynik znajdzie się w katalogu /app/dist)
RUN npm run build

# Otwieramy port, na którym z założenia działa apka NestJS
EXPOSE 3000

# Domyślne polecenie do wystartowania aplikacji po jej zbudowaniu
CMD ["npm", "run", "start:prod"]