galaxy_info:
  author: Mateusz Adamczak
  description: Role for deploying jq runtime artifact on ansible-target
  company: AGH
  license: MIT
  min_ansible_version: "2.10"

  platforms:
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - docker
    - jq
    - ci
    - deployment

dependencies: []
