pipeline {
    agent any

    environment {
        
        IMAGE_NAME = 'moj-express-bldr' 
        CONTAINER_NAME = 'express-prod-app'
        PORT = '3000'
    }

    stages {
        stage('1. Przygotowanie SCM i Czyszczenie') {
            steps {
                
                cleanWs()
                
                checkout scm
            }
        }

        stage('2. Build') {
            steps {
                script {
                    
                    echo "Budowanie obrazu kontenera na podstawie Dockerfile..."
                    sh "docker build -t ${IMAGE_NAME} ."
                }
            }
        }

        stage('3. Test') {
            steps {
                script {
                    
                    echo "Uruchamianie testów jednostkowych (npm test) w kontenerze..."
                    sh "docker run --rm ${IMAGE_NAME} npm test"
                }
            }
        }

        stage('4. Publish') {
            steps {
                script {
                    
                    echo "Pakowanie kodu produkcyjnego do artefaktu..."
                    sh "tar --exclude='./.git' --exclude='./node_modules' -czvf app-release.tar.gz ."
                    
                    
                    echo "Publikowanie w Jenkinsie..."
                    archiveArtifacts artifacts: 'app-release.tar.gz', fingerprint: true
                }
            }
        }

        stage('5. Deploy') {
            steps {
                script {
                    
                    sh "docker rm -f ${CONTAINER_NAME} || true"
                    
                    
                    echo "Uruchamianie nowej wersji aplikacji na porcie ${PORT}..."
                    sh "docker run -d --name ${CONTAINER_NAME} -p ${PORT}:${PORT} ${IMAGE_NAME}"
                    
                    echo "Smoke Test - sprawdzanie czy kontener działa bez modyfikacji..."
                    sleep 5
                    sh "docker logs ${CONTAINER_NAME}"
                }
            }
        }
    }

    post {
        always {
            
            cleanWs()
        }
        success {
            echo "Definition of Done: Sukces! Artefakt .tar.gz jest gotowy, a kontener działa."
        }
    }
}