pipeline {
    agent any

    environment {
        IMAGE_NAME = 'moj-express-bldr'
        REPO_NAME = 'sebboze3/moj-express-bldr'
        CONTAINER_NAME = 'express-prod-app'
        PORT = '3000'
        
        PROJECT_DIR = 'ITE/GCL1/SB422052/Sprawozdanie1'
    }

    stages {
        stage('1. Przygotowanie SCM i Czyszczenie') {
            steps {
                cleanWs()
                checkout scm
            }
        }

        stage('2. Build') {
            steps {
                
                dir("${PROJECT_DIR}") {
                    script {
                        echo "Budowanie obrazu kontenera na podstawie Dockerfile..."
                        sh "docker build -t ${IMAGE_NAME} ."
                    }
                }
            }
        }

        stage('3. Test') {
            steps {
                script {
                    echo "Uruchamianie testów jednostkowych w kontenerze..."
                    sh "docker run --rm ${IMAGE_NAME} npm test"
                }
            }
        }

       stage('4. Publish') {
            steps {
                
                dir("${PROJECT_DIR}") {
                    script {
                        withCredentials([usernamePassword(credentialsId: 'REGISTRY_USER_TOKEN', passwordVariable: 'DOCKER_PASS', usernameVariable: 'DOCKER_USER')]) {
                            sh "echo \$DOCKER_PASS | docker login -u \$DOCKER_USER --password-stdin"
                            
                            sh "docker tag ${IMAGE_NAME} ${REPO_NAME}:latest"
                            
                            sh "docker push ${REPO_NAME}:latest"
                            
                            sh "docker logout"
                        }
                 
                        echo "Pakowanie kodu produkcyjnego do artefaktu..."
                        
                        
                        sh "tar --exclude='./.git' --exclude='./node_modules' -czvf ../app-release.tar.gz ."
                        
                       
                        sh "mv ../app-release.tar.gz ."
                        
                        echo "Publikowanie w Jenkinsie..."
                        archiveArtifacts artifacts: 'app-release.tar.gz', fingerprint: true
                    }
                }
            }
        }

        stage('5. Deploy') {
            steps {
                script {
                    
                    sh "docker rm -f ${CONTAINER_NAME} || true"
                    
                    echo "Uruchamianie nowej wersji aplikacji na porcie ${PORT}..."
                    sh "docker run -d --name ${CONTAINER_NAME} -p ${PORT}:${PORT} ${REPO_NAME}:latest"
                    
                    echo "Smoke Test - sprawdzanie czy kontener działa bez modyfikacji..."
                    sleep 5
                    sh "docker logs ${CONTAINER_NAME}"

                    sh "docker run --rm --network host curlimages/curl -f -s -i http://localhost:${PORT}/"

                    echo "Sprawdzanie statusu zdrowia (Healthcheck)..."
                    sh "docker run --rm --network host curlimages/curl -f http://localhost:${PORT}/health"

                    sh "docker logs ${CONTAINER_NAME}"
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
        success {
            echo "Definition of Done: Sukces! Artefakt .tar.gz jest gotowy, a kontener działa."
        }
    }
}