pipeline {
    agent any
    stages {
        stage('Build: Budowanie obrazu') {
            steps {
                dir('ITE/GCL1/SB422052/Sprawozdanie1') {
                    sh 'docker build -t moj-express-lab5 .'
                }
            }
        }
        stage('Test: Uruchomienie testów') {
            steps {
                dir('ITE/GCL1/SB422052/Sprawozdanie1') {
                    
                    sh 'docker run --rm -v ${PWD}:/app -w /app node:18-alpine sh -c "npm install && npm test"'
                }
            }
        }
    }
}