pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "express-base"
        TEST_IMAGE = "express-test"
        PROJECT_DIR = "ITE/GCL3/ŁM420071/Sprawozdanie1"
    }

    stages {
        stage('Prepare') {
            steps {
                echo "Rozpoczynam proces CI/CD dla projektu w: ${PROJECT_DIR}"
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh "docker build -t ${DOCKER_IMAGE} --no-cache -f ${PROJECT_DIR}/Dockerfile.build ."
                }
            }
        }
        
        stage('Build & Run Tests') {
            steps {
                script {
                    sh "docker build -t ${TEST_IMAGE} -f ${PROJECT_DIR}/Dockerfile.test ."
                    sh "docker run --rm ${TEST_IMAGE}"
                }
            }
        }

        stage('Verify Build') {
            steps {
                sh "docker images | grep ${DOCKER_IMAGE}"
            }
        }

         stage('Publish to NPM') {
            steps {
                script {
                    withCredentials([string(credentialsId: 'npm-token-id', variable: 'NPM_TOKEN')]) {
                        sh """
                        docker run --rm ${DOCKER_IMAGE} sh -c "
                            sed -i '/\\\"name\\\":/c\\  \\\"name\\\": \\\"@freizen77/express-mdo-test\\\",' package.json &&
                            sh "npm version 5.3.${env.BUILD_NUMBER} --no-git-tag-version"
                            echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc &&
                            npm publish --access public
                        "
                        """
                    }
                }
            }
        }

        stage('Deploy & Validate') {
            steps {
                script {
                    sh "docker network create test-net || true"
                    try {
                        sh """
                        docker run -d --name express-app --network test-net node:20-alpine sh -c "
                            mkdir /app && cd /app &&
                            npm init -y &&
                            npm install @freizen77/express-mdo-test &&
                            echo 'const express = require(\\\"@freizen77/express-mdo-test\\\"); const app = express(); app.get(\\\"/\\\", (req, res) => res.send(\\\"OK\\\")); app.listen(3000);' > server.js &&
                            node server.js
                        "
                        """
                        sleep 7 
                        sh "docker run --rm --network test-net curlimages/curl:latest curl -s --retry 5 --retry-connrefused http://express-app:3000 | grep OK"
                    } finally {
                        sh "docker rm -f express-app || true"
                        sh "docker network rm test-net || true"
                    }
                }
            }
        }

        stage('Create Shrinkwrap Artifact') {
            steps {
                script {
                    sh """
                    docker run --rm \
                        -u \$(id -u):\$(id -g) \
                        -v \$(pwd):/app -w /app \
                        node:20-alpine sh -c "
                            npm install @freizen77/express-mdo-test &&
                            npm shrinkwrap
                        "
                    """
                    archiveArtifacts artifacts: 'npm-shrinkwrap.json', fingerprint: true
                }
            }
        }
    }

    post {
        always {
            sh 'docker run --rm -v $(pwd):/app -w /app alpine chown -R 1000:1000 .'
            echo 'Zakończono wykonywanie Pipeline. Sprzątanie przestrzeni roboczej...'
            cleanWs()
        }
        success {
            echo 'Sukces! Projekt opublikowany i przetestowany.'
        }
        failure {
            echo 'Błąd! Sprawdź logi w celu znalezienia przyczyny.'
        }
    }
}