FROM debian:bookworm-slim

COPY --from=my-rg-builder:latest /app/target/debian/*.deb /tmp/ripgrep.deb
RUN apt-get update \
    && apt-get install -y --no-install-recommends /tmp/ripgrep.deb \
    && rm -rf /var/lib/apt/lists/* /tmp/ripgrep.deb


LABEL org.opencontainers.image.source="https://github.com/BurntSushi/ripgrep"
LABEL org.opencontainers.image.version="14.1.1"
LABEL org.opencontainers.image.description="Runtime image ripgrep - MDO2026"

ENTRYPOINT ["rg"]
