FROM rust:1.77-slim-bookworm

WORKDIR /usr/src/ripgrep
COPY . .

RUN apt-get update && apt-get install -y pkg-config libpcre2-dev dpkg-dev && \
    cargo install cargo-deb

CMD ["cargo", "build", "--release"]