pipeline {
    agent any

    options {
        disableConcurrentBuilds()
    }

    environment {
        COMPOSE_DIR = 'ITE/GCL3/YK424367/Sprawozdanie1'
    }

    stages {
        stage('Checkout') {
            steps {
                cleanWs()
                checkout scm
            }
        }

        stage('Build image') {
            steps {
                dir("${env.COMPOSE_DIR}") {
                    sh 'docker compose build readme-aura-build'
                }
            }
        }

        stage('Test') {
            steps {
                dir("${env.COMPOSE_DIR}") {
                    sh 'docker compose build readme-aura-test && docker compose run --rm readme-aura-test'
                }
            }
        }

        stage('Deploy') {
            steps {
                dir("${env.COMPOSE_DIR}") {
                    sh """
                        set -e
                        docker compose build readme-aura-deploy
                        docker tag mdo-ite:sprawozdanie6-deploy mdo-ite:sprawozdanie6-deploy-build-${env.BUILD_NUMBER}
                    """.stripIndent()
                }
            }
        }

    }

    post {
        always {
            dir("${env.COMPOSE_DIR}") {
                sh 'rm -f jenkins-npm-publish.sh || true'
                sh 'rm -rf artifacts || true'
            }
        }
    }
}
