FROM python:3.13-slim

WORKDIR /app

COPY ..

RUN apt-get update
RUN apt-get install -y build-essential git
RUN apt-get clean

# RUN git clone https://github.com/blankdots/minimalpy.git .

RUN pip install --upgrade pip
RUN pip install pytest aiohttp==3.13.3 uvloop==0.21.0 gunicorn==25.1.0

CMD ["bash"]