pipeline {
    agent any

    environment {
        ARTIFACT_NAME = "commander-package-${BUILD_NUMBER}.tgz"
    }

    stages {
        stage('Clone') {
            steps {
                // Pobieranie z forka
                git url: 'https://github.com/kgolmento/commander.js.git', branch: 'master'
            }
        }
        
        stage('Build & Test') {
            steps {
                script {
                    // Budowa obrazu, npm install i test
                    sh 'docker build -t commander-build -f Dockerfile.build .'
                    
                    // Wyciągnięcie logów
                    sh 'docker run --rm commander-build npm test > test-logs.txt || true'
                    
                    // Wyciągnięcie artefaktu
                    sh "docker run --rm -v ${WORKSPACE}:/out commander-build sh -c 'cp /app/*.tgz /out/${ARTIFACT_NAME}'"
                }
            }
        }

        stage('Deploy (Smoke Test)') {
            steps {
                script {
                    // Kontener deploy
                    sh 'docker build -t commander-deploy -f Dockerfile.deploy .'
                    
                    // Wdrożenie i walidacja
                    sh "docker run --rm -v ${WORKSPACE}/${ARTIFACT_NAME}:/deploy/package.tgz commander-deploy sh -c 'npm install ./package.tgz && node smoke-test.js'"
                }
            }
        }

       stage('Publish') {
            steps {
                // Archiwizacja paczki w Jenkinsie
                archiveArtifacts artifacts: "${ARTIFACT_NAME}, test-logs.txt", followSymlinks: false
                
                // Publikacja do npm
                // Lekki kontener Node.js + przestrzeń robocza Jenkinsa i publish
                sh "docker run --rm -v ${WORKSPACE}:/workspace -w /workspace node:20.12.0-slim npm publish ${ARTIFACT_NAME} --dry-run"
            }
        }
    }
}