# Bazujemy na oficjalnym obrazie
FROM jenkins/jenkins:lts

# Przełączamy się na roota, żeby móc instalować pakiety
USER root

# Instalujemy wymagane narzędzia
RUN apt-get update && apt-get install -y lsb-release
RUN curl -fsSLo /usr/share/keyrings/docker-archive-keyring.asc \
  https://download.docker.com/linux/debian/gpg
RUN echo "deb [arch=$(dpkg --print-architecture) \
  signed-by=/usr/share/keyrings/docker-archive-keyring.asc] \
  https://download.docker.com/linux/debian \
  $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list

# Instalujemy TYLKO KLIENTA Dockera (docker-ce-cli)
RUN apt-get update && apt-get install -y docker-ce-cli

# Wracamy do bezpiecznego użytkownika jenkins
USER jenkins