apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-rolling
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 25%
  selector:
    matchLabels:
      app: myapp-roll
  template:
    metadata:
      labels:
        app: myapp-roll
    spec:
      containers:
      - name: myapp
        image: myapp:v2
        imagePullPolicy: Never
