apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-canary
      version: canary
  template:
    metadata:
      labels:
        app: express-canary
        version: canary
    spec:
      containers:
      - name: express-app
        image: blackcaer/express-app:22
        ports:
        - containerPort: 3000
