apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-rolling
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 25%
  selector:
    matchLabels:
      app: express-rolling
      version: stable
  template:
    metadata:
      labels:
        app: express-rolling
        version: stable
    spec:
      containers:
      - name: express-app
        image: blackcaer/express-app:21
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: express-rolling-service
spec:
  type: NodePort
  selector:
    app: express-rolling
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30002
